= PzdcDoc documentation generator
:toc:

ifndef::backend-html5,backend-docbook5[Only shown when converting to HTML5 or DocBook 5.]
NOTE: See this article in converted format: http://pzdcdoc.org/demo/README.html
endif::[]

== About
PzdcDoc is the complete ready-to-use solution, providing clear way and workflow for organizing software documentation.

Based on link:https://asciidoctor.org/docs/asciidoctorj[AsciidoctorJ], 
Java binding of the excellent software documentation framework link:https://asciidoctor.org/docs[Asciidoctor].
Thanks to 100% compatibity to AsciiDoctor, existing documentation files may be re-used.

On top of AsciiDoctor there are added the following features:
[square]
* Delivered as a single Java link:https://mvnrepository.com/artifact/org.pzdcdoc/pzdcdoc[artifact] in Maven repository for simple integration in existing build processes.
* Building documentation out of many files structured in original way with ToC.
* Preserving structure, preview of documentation is <<src/doc/demo.adoc#, available>> in GitLab and GitHub.
* Internal references checking, no more broken links.
* Produce embedded JS search over EN, RU and DE using link:https://lunrjs.com/[LunrJS].
* <<src/doc/demo#diagrams, Diagrams>> generation.
* Extension for referencing of JavaDoc by class name.
* <<src/doc/demo#snippets, Live snippets>> for extracting samples directly out of source files with simple validation of actuality.
* CSS enhancements.

== Demo
Clone the GIT repository, after execute in the directory one of the following tests.
You would need Java version 8 or higher.
Both produce result to `target/doc-out`, these files may be published on HTTP server.

=== Complex test with checking out GIT
[source]
----
gradlew buildDemoDoc
----

Extracts the project data from GIT and uses Maven artifact of PzdcDoc for running.
That sample suits for integrating to other projects. 
You may see the result here: http://pzdcdoc.org/demo

=== Simple test with local files
[source]
----
gradlew
----

Default task `buildDemoDocLocal` uses `src/doc` directory as an input and compiles classes from sources.
Good for first start and testing changes.

=== History
Initially this tool was developed for the link:https://bgerp.org[BGERP], project of Open Source ERP/CRM system.
It was successfully used there as one system with GIT stored sources for support of:
[square]
* product documentation;
* samples and articles;
* database structure

The single tool has replaced Confluence + MediaWiki + self-written DB structure describing utility in a more convenient way.
Ideally fits for continuous delivery approach, when documentation is considered as essential part of product and written, 
stored, handled together with other sources. Documentation is automatically built using GitLab CI and published, 
you may see the result link:https://bgerp.ru/doc/3.0/manual/[here].

== How does it work
[square]
* As parameter generator takes input and output directories.
* Input directory may be copied directly from project or checked out from version control to outside like `target`. 
First way is easier, in the second one may be combined doc sources out of many GIT projects.
In the input directory may be placed:
* `index.adoc` with table of contents. Only one index on the highest level will be used.
* `pzdcdoc.xml` file with AsciiDoctor attributes, these will be implicitly included in each of `.adoc` file starting from the directory, where `pzdcdoc.xml` is placed. This means, that this configuration is inherited and may be overwritten.
* The generator goes through all the files in input dir and converting all with extension `.adoc` them to `.html`.
** Directory starting from `.` are skipped.
** Includes have to be named `.adocf` to avoid converting.
** Resources (files, images) are recommended be placed in `_res` subdirectory near of referencing `.adoc` file, 
but you may reference as well any project file, it will be copied to the target directory.
* All the used references between `.adoc` are relative and automatically converted to HTML.
