= PzdcDoc documentation generator
:toc:

Based on link:https://asciidoctor.org/docs/asciidoctorj[AsciidoctorJ], 
Java binding of the excellent software documentation framework link:https://asciidoctor.org/docs[Asciidoctor].
Additionally to the information below you may have a look on the link:https://docs.google.com/presentation/d/1MEIMT9SEnepZdLMVFv2Koev3TILRGn_cNgdT25eS-Zg/edit?usp=sharing[Presentation]

== About
Initially this tool was developed for the link:https://bgerp.org[BGERP], project of Open Source ERP/CRM system.
It was successfully used there as one system with GIT stored sources for support of:
[square]
* product documentation;
* samples and articles;
* database structure

The single tool has replaced Confluence + MediaWiki + self-written DB structure describing utility in a more convenient way.
Ideally fits for continuous delivery approach, when documentation is considered as essential part of product and written, 
stored, handled together with other sources. Documentation is automatically built using GitLab CI and published, 
you may see the result link:https://bgerp.ru/doc/3.0/manual/[here].  

=== The key features
[square]
* Delivered as a single Java artifact in Maven repository for simple integration in existing build processes.
* Building documentation out of many files structured in original way with ToC.
* Preserving structure, preview of documentation is <<src/doc/demo.adoc#, available>> in GitLab and GitHub.
* Produce embedded JS search over EN, RU and DE using link:https://lunrjs.com/[LunrJS].
* Internal references checking, no more broken links.
* Extension for referencing of JavaDoc by class name.
* CSS enhancements.

== Logic
[square]
* As parameter generator takes input and output directories.
* Input directory may be taken directly from project or checked out from version control to outside like `target`. 
First way is easier, in the second one may be combined doc sources out of many GIT projects.
* In the input directory mast be placed `index.adoc` with table of contents.
* In the input directory may be placed `pzdcdoc.xml` file with different parameters.
AsciiDoctor attributes from the file are included in all of converted `.adoc` files.
* The generator goes through all the files in input dir and converting all with extension `.adoc` them to `.html`.
** Directory starting from `.` are skipped.
** Includes have to be named `.adocf` to avoid converting.
** Resources (files, images) must be placed in `_res` subdirectory near of referencing `.adoc` file, they are automatically copied.
* All the used references between `.adoc` are relative and automatically converted to HTML.

== How to test
Clone the GIT repository, after execute in the directory:
[source]
----
gradlew buildDemoDoc
----
That will build result to `target/doc-out`, these files may be published on HTTP server.
